Add custom comments to Streamer
WeTransfer/zip_tricks pull request #111
Opened 2022-02-03 06:47 UTC by pyrareae

This is a tiny patch to allow setting the commit message.

2022-02-14 10:46 UTC, grdw requested changes
Thanks for your contribution. Please add a spec for this change.

2022-02-14 10:46 UTC, grdw commented on lib/zip_tricks/zip_writer.rb
> +    comment ||= ZIP_TRICKS_COMMENT
I feel the old code actually already achieved what you had in mind. There's no need for memoizing this variable.

2022-05-28 06:19 UTC, pyrareae commented
Sorry for the long delay I have had a *lot* going on. I still intend to finish this pr by adding tests and such though.

2022-05-28 06:20 UTC, pyrareae commented on lib/zip_tricks/zip_writer.rb
> +    comment ||= ZIP_TRICKS_COMMENT
As I recall this was needed to handle a weird case with the default not being handled correctly.

2023-01-08 01:15 UTC, closed without merging