Fix hung specs running Archive Utility on macOS
WeTransfer/zip_tricks pull request #83
Opened 2020-11-06 02:34 UTC by felixbuenemann

* Use `open` to force separate copy and wait for exit
* Run using bundle id `com.apple.archiveutility` instead of path
* Temporarily change dearchive destination to cwd
* Temporarily disable showing folder in Finder after uncompress
* Check folder contents against provided list of entries

2020-11-06 12:39 UTC, julik requested changes
Not quite ok with the `defaults write` manoever. Also - where was this command hanging? at the archive utility invocation itself? And on which OS version (I am a bit of a caveman and still have Mojave on all my boxes)

2020-11-06 12:39 UTC, julik commented on spec/support/zip_inspection.rb
> +      system *%W[/usr/bin/defaults write com.apple.archiveutility dearchive-reveal-after -bool false]
I'm sorry but I think we shouldn't be doing this. Changing preferences for end-user software (even if we do it in this safe manner, and because the said software is so obtuse that it cannot be configured in a different manner) is not something a test suite for a library should be doing.

Also I actually did look into the folders that archive utility was producing - it is manual but it was working more or less OK. A case could be made for removing this test altogether though...

2020-11-06 12:39 UTC, julik commented on spec/support/zip_inspection.rb
> +    unless RbConfig::CONFIG['host_os'].match? /darwin|mac os/
Can't this be done with `RUBY_PLATFORM`?

2020-11-10 08:11 UTC, felixbuenemann commented on spec/support/zip_inspection.rb
> +    unless RbConfig::CONFIG['host_os'].match? /darwin|mac os/
Yes, except on JRuby:

```
# uname -msr
Darwin 19.6.0 x86_64
# rvm ruby-2.7 exec irb
2.7.2 :001 > RUBY_PLATFORM
 => "x86_64-darwin19"
2.7.2 :002 > RbConfig::CONFIG['host_os']
 => "darwin19.6.0"
# rvm jruby exec irb
jruby-9.2.9.0 :001 > RUBY_PLATFORM
 => "java"
jruby-9.2.9.0 :002 > RbConfig::CONFIG['host_os']
 => "darwin"
# rvm truffleruby exec irb
truffleruby-20.2.0 :001 > RUBY_PLATFORM
 => "x86_64-darwin18"
truffleruby-20.2.0 :002 > RbConfig::CONFIG['host_os']
 => "darwin"
```

Interestingly truffleruby returns a wrong value for `RUBY_PLATFORM`, since it is running on Darwin 19 not 18.

I'm not sure why the "mac os" value is in there, should be "darwin" everywhere.

2020-11-10 08:20 UTC, felixbuenemann commented on spec/support/zip_inspection.rb
> +      system *%W[/usr/bin/defaults write com.apple.archiveutility dearchive-reveal-after -bool false]
I got annoyed with the Finder window constantly popping up and the temp folder is removed at the end of the specs, so I'm curious how syou managed to inspect the folders in the split second it exists.

The folder contents are now checked using ruby during the specs, so no need for manual inspection. We could at file size or CRC checks easily as well.

Since Archive Utility is a shitty tool to automate I wouldn't mind removing it alltogether or make the tests run only manually using an rspec tag.

Unless we want automated tests to unarchive files in some unknown destination on the developers Mac, there's no way around changing the defaults, unless we just check the values and crash if configured badly.

Given that, changing the defaults and setting them back with ensure seems a good compromise.

2020-11-10 08:32 UTC, felixbuenemann commented
> Also - where was this command hanging? at the archive utility invocation itself? And on which OS version (I am a bit of a caveman and still have Mojave on all my boxes)

I'm on 10.15.7, but it shouldn't really matter. The problem is, that most macOS GUI apps only start one instance and then stay running. So the first time you start Archive Utility it starts and then just keeps running and never quits unless you manually switch to the app and do Cmd+Q or Ctrl+C in the Terminal.

By using pretty much all of the flags to "open" we tell macOS to launch a new instance of the app in the background, even if one is already running and wait for it to exit.

You also can just pass the filename as an argument to the "Archive Utility" binary, it will be ignored, you have to pass is  using open. That probably worked on older macOS versions and is the reason that the app hangs, even if it is the first instance to be launched.

2020-11-10 09:08 UTC, felixbuenemann commented on spec/support/zip_inspection.rb
> +      system *%W[/usr/bin/defaults write com.apple.archiveutility dearchive-reveal-after -bool false]
@julik By the way, Archive Utility is using libarchive under the hood (on macOS 10.15.7 libarchive/3.3.2), so another way would be to use a gem like "ffi-libarchive" to dlopen it and uncompress the zip.

That would have the benefit of being able to run on Linux as well.

I just tested it and it works fine even on JRuby.

One drawback is that by default it will use a newer libarchive if it is installed by homebrew and only fall back to the system one if not found.

2020-11-16 19:04 UTC, closed without merging